#pragma config(Sensor, in5,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in6,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in7,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, dgtl1,  stopButton,     sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393, openLoop)
#pragma config(Sensor, dgtl7,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  rightEncoder,   sensorQuadEncoder)/*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses 3 VEX Line Follower Sensors to track a black line on a light(er) surface.       *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Lighting conditions, line darkness, and surface lightness change from place to place,       *|
|*        so the value of 'threshold' may need to be changed to better suit your environment.         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down           *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++


task stopMyTask(){
	while(SensorValue[stopButton] == 0 && vexRT[Btn8R]==0){
	}
	StopAllTasks();
}


task main()
{
	StartTask(stopMyTask);
	int power = 63;

  int threshold = 1800;

  SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
	wait1Msec(5000);
  while(SensorValue[rightEncoder] < 1400)
  {
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+
    displayLCDCenteredString(0, "LEFT  CNTR  RGHT");        //  Display   |
    displayLCDPos(1,0);                                     //  Sensor    |
    displayNextLCDNumber(SensorValue(lineFollowerLEFT));    //  Readings  |
    displayLCDPos(1,6);                                     //  to LCD.   |
    displayNextLCDNumber(SensorValue(lineFollowerCENTER));  //            |
    displayLCDPos(1,12);                                    //  L  C  R   |
    displayNextLCDNumber(SensorValue(lineFollowerRIGHT));   //  x  x  x   |


		// CENTER sensor sees dark:
			if(SensorValue(lineFollowerLEFT) > threshold && SensorValue(lineFollowerRIGHT) > threshold)
			{
			  motor[leftMotor]  = power;
			  motor[rightMotor] = -power;
			}
			if(SensorValue(lineFollowerLEFT) < threshold && SensorValue(lineFollowerRIGHT) > threshold)
			{
			  // counter-steer left:
			  motor[leftMotor]  = power;
			  motor[rightMotor] = -20;
			}
			 // RIGHT sensor sees dark:
			if(SensorValue(lineFollowerRIGHT) < threshold && SensorValue(lineFollowerLEFT) > threshold)
			{
			  // counter-steer right:
			  motor[leftMotor]  = 30;
			  motor[rightMotor] = -power;
			}
		}
		motor[leftMotor]  = 0;
		motor[rightMotor] = 0;
		SensorValue(rightEncoder) = 0;
		wait1Msec(500);
		while(SensorValue(rightEncoder) < 700)
			{
					if(SensorValue(lineFollowerLEFT) > threshold && SensorValue(lineFollowerRIGHT) > threshold)
			{
			  motor[leftMotor]  = power;
			  motor[rightMotor] = -power;
			}
			if(SensorValue(lineFollowerLEFT) < threshold && SensorValue(lineFollowerRIGHT) > threshold)
			{
			  // counter-steer left:
			  motor[leftMotor]  = power;
			  motor[rightMotor] = 5;
			}
			 // RIGHT sensor sees dark:
			if(SensorValue(lineFollowerRIGHT) < threshold && SensorValue(lineFollowerLEFT) > threshold)
			{
			  // counter-steer right:
			  motor[leftMotor]  = 0;
			  motor[rightMotor] = -power;
			}
			}

}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
